config/routes.rb
Rails.application.routes.draw do
  root to: 'tasks#index'
  resources :tasks
  resources :users, only: [:new, :create, :show]
  resources :sessions, only: [:new, :create, :destroy]
  resources :labels, except: [:show]
  namespace :admin do
    resources :users
  end
end

app/models/label.rb
class Label < ApplicationRecord
  belongs_to :user
  has_many :labelings, dependent: :destroy
  has_many :tasks, through: :labelings, source: :task

  validates :name, presence: true, length: { maximum: 30 }, uniqueness: true
end

app/controllers/labels_controller.rb
class LabelsController < ApplicationController
  before_action :set_label, only: [:edit, :update, :destroy]
  before_action :authenticate_user

  def index
    @labels = current_user.labels
    @labels = @labels.page(params[:page]).per(8)
  end

  def new
    @label = Label.new
  end

  def create
    @label = current_user.labels.build(label_params)
    if @label.save
      redirect_to labels_path, flash: {success: t('notice.label.create', label: @label.name)}
    else
      flash.now[:danger] = t('alert.label.create')
      render :new
    end
  end

  def edit; end

  def update
    if @label.update(label_params)
      redirect_to labels_path, flash: {success: t('notice.label.update', label: @label.name)}
    else
      flash.now[:danger] = t('alert.label.update')
      render :edit
    end
  end

  def destroy
    @label.destroy
    redirect_to labels_path flash: {success: t('notice.label.destroy', label: @label.name)}
  end

  private
  def set_label
    @label = Label.find(params[:id])
  end

  def label_params
    params.require(:label).permit(:name)
  end
end

app/views/labels/_form.html.erb
<div class="form-horizontal" role="form">
  <%= form_with(model: @label, local: true) do |f| %>
  <% if @label.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger">
        <h2><%= t('errors.template.header', count: @label.errors.count) %></h2>
        <ul>
          <% @label.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>
  <div class="form-group title row">
    <div class="col-xs-3 control-label">
      <%= f.label :name %>
    </div>
    <div class="col-xs-7">
      <%= f.text_field :name, class: 'form-control' %>
    </div>
  </div>
  <br>
  <div class="form-group">
    <%= f.submit class: 'btn btn-primary'%>
  </div>
  <% end %>
</div>

app/views/labels/edit.html.erb
<div class="page_item">
  <h2><%= t('labels.Editing Label') %></h2>
  <br>
  <%= render 'form', post: @label %>
  <br>
  <%= link_to t('link.label.Index'), labels_path, class: 'btn btn-info' %>
</div>

app/views/labels/index.html.erb
<h2><%= t('labels.Index') %></h2>
<br>
<div class="btn_new">
  <%= link_to t('link.label.New'), new_label_path, class: 'btn btn-primary' %>
</div>
<table class="table index">
  <tr>
    <th><%= Label.human_attribute_name(:name) %></th>
    <th class="text-center"><%= Label.human_attribute_name(:created_at) %></th>
    <th class="text-center"><%= Label.human_attribute_name(:updated_at) %></th>
    <th></th>
    <th></th>
  </tr>
  <div class="table item">
    <% @labels.each do |label| %>
      <tr class="task_row">
        <td><p class="label_item"><%= label.name %></p></td>
        <td class="text-center"><%= l label.created_at %></td>
        <td class="text-center"><%= l label.updated_at %></td>
        <td><%= link_to t('link.Edit'), edit_label_path(label), class: 'btn btn-success btn-sm' %></td>
        <td><%= link_to t('link.Destroy'), label_path(label), class: 'btn btn-danger btn-sm', method: :delete, data: {confirm: t('message.label.Are you sure?', label: label.name)} %></td>
      </tr>
    <% end %>
  </div>
  <%= page_entries_info @labels %>
</table>
<div class="page">
  <%= paginate @labels %>
</div>

app/views/labels/new.html.erb
<div class="page_item">
  <h2><%= t('labels.New Label') %></h2>
  <br>
  <%= render 'form', post: @label %>
  <br>
  <%= link_to t('link.label.Index'), labels_path, class: 'btn btn-info' %>
</div>