config/routes.rb
Rails.application.routes.draw do
  root to: 'tasks#index'
  resources :tasks
  resources :users, only: [:new, :create, :show]
  resources :sessions, only: [:new, :create, :destroy]
  resources :labels, except: [:show]
  namespace :admin do
    resources :users
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tasks, dependent: :destroy
  has_many :labels, dependent: :destroy
  
  with_options presence: true do
    validates :name, length: { maximum: 50 }
    validates :email, length: { maximum: 255 }, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }, uniqueness: true
    validates :password, length: {minimum: 6}, on: :create
  end

  before_validation {email.downcase!}
  has_secure_password

  after_update :forbid_last_admin_update
  before_destroy :forbid_last_admin_destroy

  def forbid_last_admin_update
    if User.where(admin: true).count < 1
      errors.add(:admin, I18n.t('errors.messages.last_admin_user'))
      raise ActiveRecord::Rollback
    end
  end

  def forbid_last_admin_destroy
    throw(:abort) if User.where(admin: true).count == 1 && self.admin
    errors.add(:admin, I18n.t('errors.messages.last_admin_user'))
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user
  before_action :require_admin

  def index
    @users = User.all.includes(:tasks)
    @users = @users.page(params[:page]).per(8)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to admin_users_path, flash: {success: t('notice.admin.user.create', user: @user.name)}
    else
      flash.now[:danger] = t('alert.users.create')
      render :new
    end
  end

  def show; end

  def edit; end

  def update
    if @user.update(user_params)
      redirect_to admin_user_path(@user), flash: {success: t('notice.admin.user.update', user: @user.name)}
    else
      flash.now[:danger] = t('alert.users.update')
      render :edit
    end
  end

  def destroy
    if @user.destroy
      redirect_to admin_users_path, flash: {success: t('notice.admin.user.destroy', user: @user.name)}
    else
      redirect_to admin_users_path, flash: {danger: t('alert.users.destroy', user: @user.name)}
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :admin)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_admin
    redirect_to tasks_path, flash: {danger: t('alert.users.Another user')} unless current_user.admin?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user, only: [:show]
  before_action :ensure_correct_user, only: [:show]
  before_action :restrict_login_user, only: [:new, :create]
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user), flash: {success: t('notice.user.create', user: @user.name)}
    else
      flash.now[:danger] = t('alert.users.create')
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :admin)
  end
end

app/views/admin/users/_form.html.erb
<%= form_with(model: [:admin, @user], local: true) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger">
        <h2><%= t('errors.template.header', count: @user.errors.count) %></h2>
        <ul>
          <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>
  <div class="form-group title row">
    <div class="col-xs-4 control-label">
      <%= f.label :name %>
    </div>
    <div class="col-xs-4">
      <%= f.text_field :name, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group title row">
    <div class="col-xs-4 control-label">
      <%= f.label :email %>
    </div>
    <div class="col-xs-4">
      <%= f.text_field :email, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group title row">
    <div class="col-xs-4 control-label">
      <strong><%= t('admin.role') %></strong>
    </div>
    <div class="col-xs-1">
      <%= f.label :admin, class: 'form-check-label' do %>
        <%= f.check_box :admin, {class: 'form-check-input'}, "true", "false" %>
      <% end %>
    </div>

  </div>
  <div class="form-group title row">
    <div class="col-xs-4 control-label">
      <%= f.label :password %>
    </div>
    <div class="col-xs-4">
      <%= f.password_field :password, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group title row">
    <div class="col-xs-4 control-label">
      <%= f.label :password_confirmation %>
    </div>
    <div class="col-xs-4">
      <%= f.password_field :password_confirmation, class: 'form-control' %>
    </div>
  </div>
  <br>
  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/admin/users/edit.html.erb
<div class="form-horizontal" role="form">
  <h2><%= t('users.Edit User', user: @user.name) %></h2>
  <br>
  <%= render 'form', locals: {user: @user} %>
  <br><br>
  <%= link_to t('link.user.Index'), admin_users_path, class: 'btn btn-info' %>
</div>

app/views/admin/users/index.html.erb
<h2><%= t('users.Index') %></h2>
<br>
<div class="btn_new">
  <%= link_to t('link.user.New'), new_admin_user_path, class: 'btn btn-primary' %>
</div>
<table class="table index">
  <tr class="text-center">
    <th class="text-center"><%= User.human_attribute_name(:name) %></th>
    <th class="text-center"><%= User.human_attribute_name(:email) %></th>
    <th class="text-center"><%= User.human_attribute_name(:admin) %></th>
    <th class="text-center"><%= t('users.task_count') %></th>
    <th class="text-center"><%= User.human_attribute_name(:created_at) %></th>
    <th class="text-center"><%= User.human_attribute_name(:updated_at) %></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  <div class="table item">
    <% @users.each do |user| %>
      <tr class="task_row">
        <td class="text-center"><%= user.name %></td>
        <td class="text-center"><%= user.email %></td>
        <td class="text-center"><%= t("admin.#{user.admin}") %></td>
        <td class="text-center"><%= user.tasks.count %></td>
        <td class="text-center"><%= l user.created_at %></td>
        <td class="text-center"><%= l user.updated_at %></td>
        <td><%= link_to t('link.Show'), admin_user_path(user), class: 'btn btn-primary btn-sm' %></td>
        <td><%= link_to t('link.Edit'), edit_admin_user_path(user), class: 'btn btn-success btn-sm' %></td>
        <td><%= link_to t('link.Destroy'), admin_user_path(user), class: 'btn btn-danger btn-sm', method: :delete, data: {confirm: t('message.user.Are you sure?', user: user.name)} %></td>
      </tr>
    <% end %>
  </div>
  <%= page_entries_info @users %>
</table>
<div class="page">
  <%= paginate @users %>
</div>

app/views/admin/users/new.html.erb
<div class="form-horizontal" role="form">
  <h2><%= t('users.Create User') %></h2>
  <br>
  <%= render 'form', locals: {user: @user} %>
</div>

app/views/admin/users/show.html.erb
<div class="container show_item">
  <h2><%= t('users.Show User', user: @user.name) %></h2>
  <br><br>
  <table class="table">
    <tbody class="table show">
      <tr>
        <th><%= User.human_attribute_name(:id) %></th>
        <td><%= @user.id %></td>
      </tr>
      <tr>
        <th><%= User.human_attribute_name(:name) %></th>
        <td><%= @user.name %></td>
      </tr>
      <tr>
        <th><%= User.human_attribute_name(:email) %></th>
        <td><%= @user.email %></td>
      </tr>
      <tr>
        <th><%= User.human_attribute_name(:admin) %></th>
        <td><%= t("admin.#{@user.admin}") %></td>
      </tr>
    </tbody>
  </table>
  <%= link_to t('link.Edit'), edit_admin_user_path(@user), class: 'btn btn-success' %>
  <%= link_to t('link.Destroy'), admin_user_path(@user), class: 'btn btn-danger', method: :delete, data: {confirm: t('message.user.Are you sure?', user: @user.name)} %>
  <%= link_to t('link.user.Index'), admin_users_path, class: 'btn btn-info' %>
  <br><br>
  <table class="table index">
    <tr>
      <th><%= Task.human_attribute_name(:title) %></th>
      <th><%= Task.human_attribute_name(:content) %></th>
      <th><%= Task.human_attribute_name(:deadline) %></th>
      <th><%= Task.human_attribute_name(:created_at) %></th>
      <th><%= Task.human_attribute_name(:status) %></th>
      <th><%= Task.human_attribute_name(:priority) %></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
    <div class="table item">
      <% @user.tasks.each do |task| %>
        <tr class="task_row">
          <td><%= task.title %></td>
          <td><%= task.content %></td>
          <td><%= l task.deadline %></td>
          <td><%= l task.created_at %></td>
          <td><%= t("task.status.#{task.status}") %></td>
          <td><%= t("task.priority.#{task.priority}") %></td>
          <td><%= link_to t('link.Show'), task_path(task), class: 'btn btn-primary btn-sm' %></td>
          <td><%= link_to t('link.Edit'), edit_task_path(task), class: 'btn btn-success btn-sm' %></td>
          <td><%= link_to t('link.Destroy'), task_path(task), class: 'btn btn-danger btn-sm', method: :delete, data: {confirm: t('message.Are you sure?', title: task.title)} %></td>
        </tr>
      <% end %>
    </div>
  </table>
</div>