config/routes.rb
Rails.application.routes.draw do
  root to: 'tasks#index'
  resources :tasks
  resources :users, only: [:new, :create, :show]
  resources :sessions, only: [:new, :create, :destroy]
  resources :labels, except: [:show]
  namespace :admin do
    resources :users
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskleafApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#gnavi">
            <span class="sr-only">taskleaf</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">taskleaf</a>
        </div>
        <div id="gnavi" class="collapse navbar-collapse justify-content-end">
          <ul class="nav navbar-nav navbar-right">
            <% if logged_in? %>
              <li><%= link_to current_user.name, user_path(current_user.id) %></li>
              <% if current_user.admin? %>
                <li><%= link_to t('link.user.Index'), admin_users_path %></li>
              <% end %>
              <li><%= link_to t('link.Index'), tasks_path %></li>
              <li><%= link_to t('link.label.Index'), labels_path %></li>
              <li><%= link_to t('link.session.Destroy'), session_path(current_user.id), method: :delete %></li>
            <% else %>
              <li><%= link_to t('link.user.New'), new_user_path %></li>
              <li><%= link_to t('link.session.New'), new_session_path %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "alert alert-#{key}") %>
    <% end %>
    <div class="container">
      <%= yield %>
    </div>
      <div class="footer">
        <div class="footer_content">
          <p>taskleaf</p>
          <p>© 2020 T-ogino</p>
        </div>
      </div>
  </body>
</html>